letired/tooltime

Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20170424150655_devise_create_users.rb, db/migrate/20170424150857_add_names_to_user.rb, db/schema.rb
Just basic user Model with user id first and last name.
=> basic user model created

app/assets/stylesheets/config/_variables.scss, app/assets/stylesheets/layout/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
Proposed design for the home page (with a search bar in the banner), and the footer. 
+ Initial design modified to include a simple_form on the home page (NOT tested because I have not generated a Tool model).
=> design for home page with banner and footer

app/models/tool.rb, app/models/user.rb, db/migrate/20170424154724_create_tools.rb, db/schema.rb
added model and associations (user has many tools, tool belongs to user)
=> added tool model

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/init_attachinary.js, app/views/layouts/application.html.erb, config/application.rb, config/routes.rb, db/migrate/20170425084919_create_attachinary_tables.attachinary.rb, db/schema.rb
pretty general cloudinary and attachinary setup
=> added generic cloudinary and attachinary config

app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/users/bookings.html.erb, app/views/users/tools.html.erb, config/routes.rb
with actions 'bookings' and 'tools', created respective paths in the controller
=> added users controller 

app/views/tools/_form.html.erb
=> passing that user idto bookings

app/controllers/tools_controller.rb
worx for now, could possibly be optimized/shortened in the future
=> quick and dirty fix

app/controllers/users_controller.rb, app/models/tool.rb, app/views/devise/registrations/new.html.erb
=> model validations and first and last name added to signup form

app/views/tools/_form.html.erb, app/views/tools/show.html.erb
=> standardized the form a lil...still need a picture

app/views/tools/_form.html.erb, app/views/tools/new.html.erb
=> standardized the buttons

app/views/layouts/application.html.erb
=> added a super geeky lil title bar icon : )

app/views/users/bookings.html.erb
=> a nice users#bookings page

app/views/tools/_form.html.erb
=> made it mo betta

app/views/users/bookings.html.erb
=> fun with icons

app/assets/stylesheets/pages/_home.scss, app/views/users/bookings.html.erb, app/views/users/tools.html.erb
=> last minute polishing job

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/tools_controller.rb, app/models/tool.rb, app/views/layouts/application.html.erb, app/views/tools/show.html.erb, config/initializers/geocoder.rb, db/migrate/20170427091159_add_coordinates_to_tools.rb, db/schema.rb
=> works but could use some design features

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/bookings/_form.html.erb, app/views/layouts/application.html.erb
=> this really made me love datepicker

app/views/bookings/_form.html.erb
now you can't pick any dates in the past and also you won't be able to reserve tools more than two weeks into the future
=> limited the possible range to book tools

app/controllers/tools_controller.rb, app/models/tool.rb, app/views/pages/home.html.erb, app/views/tools/_form.html.erb, app/views/tools/show.html.erb, db/migrate/20170427212858_add_city_to_tools.rb, db/schema.rb
Now we give the choice to limit our search by city on the home page and we also differentiate between address and city to make tool location more organized and structured. This means we have to work on a new seed though.
=> added a 'by city' filter to start page and implemented logic

app/mailers/application_mailer.rb
=> tiny adjustment

app/controllers/tools_controller.rb, app/views/devise/passwords/new.html.erb, app/views/tools/index.html.erb
=> added a search by filter function, could use design
